//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
namespace RazorWebSample.Controllers
{
	
    [Authorize]
    public class AccountController : Controller
    {
        
        public AccountController ()
        {
        }

		public ActionResult ABBC()
		{
			return View();
		}
		public ActionResult CCBBA()
		{
			return View();
		}
		public ActionResult CCCD()
		{
			return View();
		}
		public ActionResult EEFF()
		{
			return View();
		}
		public ActionResult hell()
		{
			return View();
		}
    }
}