using System;
using System.Globalization;
using RazorEngine;
using RazorEngine.Configuration;
using RazorEngine.Templating;
using RazorEngine.Text;
using RazorTransformLibary.Data;
using RazorTransformLibary.Utils;

namespace RazorTransformLibary.Generator
{
    public class RazorGenerator : IBaseGenerator
    {
        private string headerString =
            "//------------------------------------------------------------------------------\r\n"
            + "// <auto-generated>\r\n"
            + "//     This code was generated from a template.\r\n"
            + "//\r\n"
            + "//     Manual changes to this file may cause unexpected behavior in your application.\r\n"
            + "//     Manual changes to this file will be overwritten if the code is regenerated.\r\n"
            + "// </auto-generated>\r\n"
            + "//------------------------------------------------------------------------------\r\n";
        private string _filePath;
        private object _modeldata;
        private readonly bool _isPath;
        private ITemplateSource _templateSource;
        private ITemplateKey _templateKey;
        private IRazorEngineService _engine;
        public RazorFileTemplate RazorTemplate { get; private set; }
        private string _result;
        private string _fileContent;
        public RazorGenerator()
        {

        }
        public RazorGenerator(string filePathOrCotent, object modeldata, bool isPath = true)
        {
            _filePath = _fileContent = filePathOrCotent;
            _modeldata = modeldata;
            _isPath = isPath;
        }

        public void Init()
        {
            if (_isPath)
            {
                _fileContent = FileUtils.ReadFileContent(_filePath);
            }
            //load file setting with config in header
            RazorTemplate = FileTemplateManager.LoadFileTemplate(_fileContent, false);
            //create config for razor engine
            //http://antaris.github.io/RazorEngine/
            var config = new TemplateServiceConfiguration();
            config.EncodedStringFactory = new RawStringFactory();
            config.BaseTemplateType = typeof(CustomTemplateBase<>);
            config.TemplateManager = new DelegateTemplateManager();
            var referenceResolver = new MyIReferenceResolver();
            referenceResolver.DllFolder = RazorTemplate.InputDllFolder;
            config.ReferenceResolver = referenceResolver;
            _engine = RazorEngineService.Create(config);
            _templateKey = Engine.Razor.GetKey(MyTemplateKey.MAIN_TEMPLATE);
            //check template is compile
            if (!_engine.IsTemplateCached(_templateKey, null))
            {
                var data = RazorTemplate.TemplateData;
                _templateSource = new LoadedTemplateSource(data);
                _engine.AddTemplate(_templateKey, _templateSource);
                _engine.Compile(_templateKey, _modeldata.GetType());
            }
        }

        public string Render()
        {
            _result = _engine.Run(_templateKey, _modeldata.GetType(), _modeldata).Trim();
            //put header for result code
            if (RazorTemplate.IsHeader)
            {
                _result = headerString + _result;
            }
            return _result;
        }

        public void OutPut()
        {
            try
            {
                if (!string.IsNullOrWhiteSpace(RazorTemplate.OutPutFile))
                {
                    FileUtils.WriteToFile(RazorTemplate.OutPutFile, _result.Trim());
                }
            }
            catch (Exception)
            {

                throw new Exception("Can't write file with path +" + RazorTemplate.OutPutFile);
            }

        }
    }
    [Serializable]
    public class CustomTemplateBase<X> : TemplateBase<X>
    {
        private string _tabString = "\t";

        /// <summary>
        /// Simple write @ for .cshtml file
        /// </summary>
        /// <returns></returns>
        public string R2()
        {
            return "@";
        }
        /// <summary>
        /// Write Raw String file
        /// </summary>
        /// <param name="str">Raw</param>
        /// <returns></returns>
        public string R(string str)
        {
            return str;
        }
        public string NL
        {
            get { return Environment.NewLine; }
        }

        public string T
        {
            get
            {
                return _tabString;
            }
        }
        /// <summary>
        /// Write line with string
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        public string WF(string str)
        {
            return WF(0, str);
        }
        /// <summary>
        /// Write line and add some \t in start of line
        /// </summary>
        /// <param name="numTab">number of \t added</param>
        /// <param name="data">line data</param>
        /// <returns></returns>
        public string WF(int numTab, string data = default(string))
        {
            string result = "";
            for (var i = 0; i < numTab; i++)
            {
                result += _tabString;
            }
            return result + data + Environment.NewLine;
        }

        public string WF(string str, params string[] value)
        {
            return WF(0, str, value);
        }

        public string WF(int num, string str, params string[] value)
        {
            string result = "";
            for (var i = 0; i < num; i++)
            {
                result += _tabString;
            }
            return result + string.Format(str, value) + Environment.NewLine;
        }

        public string ToTitleCase(string str)
        {
            return CultureInfo.CurrentCulture.TextInfo.ToTitleCase(str.ToLower());
        }
    }
}
